TEST_OUTPUT_TAG: "Test-Tag"
BITSTREAM_EXTENSION: "av2"
DESIRED_CTX_LIST:
 - eob_flag_cdf16
 - eob_flag_cdf32
eob_flag_cdf16: "av2_default_eob_multi16_cdfs"
eob_flag_cdf32: "av2_default_eob_multi32_cdfs"
